FROM ubuntu:18.04
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
RUN touch /etc/apt/sources.list

RUN echo '\
deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse\n\
deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse\n\
deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse\n\
deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse\n\
deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse\n\
deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse\n\
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse\n\
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse\n\
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse\n\
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse\
' > /etc/apt/sources.list

RUN cat /etc/apt/sources.list
RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install openssh-server -y
RUN apt-get install gdb -y
RUN apt-get install git -y
RUN apt-get install unzip -y
RUN apt-get install libssl-dev -y

RUN service ssh restart